export const TEXT = {
    STAFF: "Nhân viên",
    REPORT: "Báo cáo",
    SETTING: "Setting",
    LOGIN: "Log in",
    LOGOUT: "Log out",
    USERNAME: "Username",
    EMAIL: "Email",
    PASSWORD: "Password",
    REMEMBER_ME: "Remember me",
    FORGOT_PASSWORD: "Forgot password",
    IS_REQUIRED: "is required",
    ADD_NEW: "Thêm mới",
    ADD_REPORT: "Thêm báo cáo",
    NAME: "Tên",
    CASH: "Tiền mặt",
    TOTAL: "Tổng tiền",
    WORK_SHIFT: "Ca làm việc",
    SUBMIT_SHIFT: "Chốt ca",
    DATE: "Ngày",
    CHECK_IN: "Giờ vào",
    CHECK_OUT: "Giờ ra",
    REVENUE: "Doanh thu",
    SAVE: "Save",
};
