import React from "react";
import type { Metadata } from "next";
import AuthProvider from "./AuthProvider";
import Layout from "@/components/layouts";
import CustomThemeProvider from "@/theme/CustomThemeProvider";
import { getServerSession } from "next-auth";
import { Roboto } from "next/font/google";
import { ProfileProps } from "@/types/profileProps";
import { authOptions } from "@/utils/authOptions";
import "./globals.css";
import Loading from "@/components/Loading";

const roboto = Roboto({
    weight: ["400", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session: ProfileProps | null = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={roboto.className}>
                <CustomThemeProvider>
                    <main>
                        <Loading />
                        <AuthProvider>
                            {session ? (
                                <Layout session={session}>{children}</Layout>
                            ) : (
                                children
                            )}
                        </AuthProvider>
                    </main>
                </CustomThemeProvider>
            </body>
        </html>
    );
}
