import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { getServerSession } from "next-auth";
import Layout from "@/components/layouts";
import AuthProvider from "./AuthProvider";
import { ProfileProps } from "@/types/profileProps";
import { authOptions } from "@/utils/authOptions";
import "./globals.css";

const roboto = Roboto({
    weight: ["400", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session: ProfileProps | null = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={roboto.className}>
                <main>
                    <AuthProvider>
                        {session ? (
                            <Layout session={session}>{children}</Layout>
                        ) : (
                            children
                        )}
                    </AuthProvider>
                </main>
            </body>
        </html>
    );
}
