import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Layout from "@/components/layouts";
import "./globals.css";

const roboto = Roboto({
    weight: ["400", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <main>
                    <Layout>{children}</Layout>
                </main>
            </body>
        </html>
    );
}
